steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - docker login --username=$$USERNAME --password=$$PASSWORD
    entrypoint: bash
    secretEnv:
      - USERNAME
      - PASSWORD
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - 'docker build -t $$USERNAME/$$REPOSITORY:$$TAG .'
    entrypoint: bash
    secretEnv:
      - USERNAME
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - 'docker push $$USERNAME/$$REPOSITORY:$$TAG'
    entrypoint: bash
    secretEnv:
      - USERNAME
options:
  env:
    - PROJECT_ID=nifty-bird-321722
    - REPOSITORY=django_crud
    - TAG=v$BUILD_ID.$SHORT_SHA
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/dockerhub-password/versions/1
      env: PASSWORD
    - versionName: projects/$PROJECT_ID/secrets/dockerhub-username/versions/1
      env: USERNAME

# Refrences:
# https://cloud.google.com/build/docs/configuring-builds/create-basic-configuration
# https://cloud.google.com/build/docs/interacting-with-dockerhub-images#pushing_images_to_docker_hub
# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
